bugfix: Allow generating test reports from forks

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,13 +28,11 @@ jobs:
         uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
       - name: Build with Gradle
         run: ./gradlew build
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
+      - uses: actions/upload-artifact@v4  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
         with:
-          name: JUnit Tests ( ${{ matrix.OS }} )
-          path: "**/test-results/**/*.xml"
-          reporter: java-junit
+          name: test-results
+          path: build/test-results/test
       - name:  Show version
         run: ./gradlew :printVersion
       - name: Publish snapshot
